Final_Download_Pro_X/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Final_Downloader.urls')),
    path('users/', include('User.urls')),
]

Final_Downloader/urls.py
from django.urls import path

from . import views

app_name = 'Final_Downloader'



urlpatterns = [
    path(r'', views.new_task, name='new_task'),
    path(r'download_task/', views.download_task, name='download_task'),
    path(r'download_status/', views.download_status, name='download_status'),
    path(r'search/<str:key_word>', views.search_video, name='search_video'),
    path(r'search/video/<str:video_id>', views.display_video_info, name='display_video_info'),
    path(r'transmit/<str:video_id>', views.transmit_file, name='transmit_task')
]

User/urls.py
"""Defines URL patterns for User""" 

from django.urls import path, include

from . import views

app_name = 'Users' 
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls'), name='login'),

    # Registration page.
    path('register/', views.register, name='register'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Final Download Pro X</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <aside>
        <p>
            <a href="{% url 'Final_Downloader:new_task' %}">Final-Download-Pro-X</a> - 
            {% if user.is_authenticated %}
                Hello, {{ user.username }}.
                <a href="{% url 'Users:logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'Users:login' %}">Log in</a> - 
                <a href="{% url 'Users:register' %}">Register</a>
            {% endif %}   
        </p>
    </aside>
    {% block content %}{% endblock content %}
</body>
</html>